title: 烫烫烫烫烫烫烫烫
email: hugo.colombo23@gmail.com
author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: wineway
  location: jiangsu - China
  description: "studying CV"  
description: 翻译与学习笔记
baseurl: "/"
url: https://wineway.github.io/
twitter_username: wangyuweihx
github_username:  wineway
github_url: https://wineway.github.io
# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
