title: 烫烫烫烫烫烫烫烫烫烫烫烫
email: wangyuweihx@gmail.com
author:
  picture: http://i1.piimg.com/1949/3373f861bd9f6555.png #URL FORMAT
  name: wineway
  location: Jiangsu - China
  description: "studying CV"  
description: 学习笔记与翻译
baseurl: "/"
url: https://hugocarreira.github.io/jekyll-vision-casper-theme
twitter_username: wangyuweihx
github_username:  wineway
github_url: https://wineway.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
